---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

  - job_name: python
    static_configs:
    - targets:
        - localhost
      labels:
        job: adsl_python
        __path__: /var/log/adsl_python/*

  - job_name: radius
    static_configs:
    - targets:
        - localhost
      labels:
        job: adsl_radius
        __path__: /var/log/adsl_radius/*
